### ISSUE TITLE
Set distance filter

### ISSUE THREAD

**Issue by auberginekenobi** [ay-lab/mustache#10]
It looks like Mustache has a parameter to change the maximum allowable distance between loops. This is not on the github README but it is on the command line help summary:
>   -d DISTFILTER, --distance DISTFILTER
>                       REQUIRED: Maximum distance (in bp) allowed between loop loci

Based on Mustache output, I don't think the -d parameter is working...
Input:
`mustache -f ./MB268.allValidPairs.hic -r 10kb -o MB268-mustache-10kb.hg38.bedpe -ch 1 -d 11000000`
Output:
```
The distance limit is set to 2Mbp
Reading contact map...
HiC version:  8
Normalizing contact map...
```

**Comment by ay-lab** [comment]
Hi and thanks for using our tool. Yes, that is because we have only tested mustache for 2MB distance range. However, you can change that manually in the code (e.g., add "distFilter = 3000000" at line 883).

**Comment by charlesfeigin** [comment]
I think something else may be wrong with the code, as I get loops considerably 250kb when setting -d to 250,000 despite it being well within the 2mb tested range.

**Comment by hrahmanin** [comment]
I think changing distance might work, however, even if the distFilter changes, the output still prints 'The distance limit is set to 2Mbp'. 

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/447b1aab-0444-4b5c-815b-cd40789cf8c8" />

**Comment by cemilcan98** [comment]
Hi, I have made the changes to distFilter to allow values up to 10Mbp.
