### ISSUE TITLE
-ch parameter

### ISSUE THREAD

**Issue by gabedolpten** [ay-lab/mustache#12]
Is there any way to run it for all chromosomes? What inputs can one give to this parameter?

**Comment by ay-lab** [comment]
Hello, unfortunately right now we don't have that option. You have to provide the chromosome name you want to run mustache on, e.g., "-ch chr1" or "-ch 1" depends on the format/names your .hic or .cool file is using.

**Comment by ay-lab** [comment]
I forgot to mention that this option has been added for .hic, .mcool and .cool files now. So, if you don't specify the chromosome name mustache runs on all the chromosomes and output the results in the output file you specify by -o parameter.
