### ISSUE TITLE
Loop calling with very high resolutions (100s of bp)

### ISSUE THREAD

**Issue by gabedolpten** [ay-lab/mustache#13]
Hey, do you have any advice for calling loops on mcool files that have 100s of bp resolution? The loops I am getting now seem to be highly overfitting to the data.

**Comment by ay-lab** [comment]
Hi. Can you tell us what parameter/values you are using? Also, what do you mean by 100s? We know it works fine with 500-600bp but we haven't tested it much on higher resolutions yet. Do you have Hi-C or Micro-C? I can take a closer look if you share can some data.

**Comment by gabedolpten** [comment]
Here is my command right now. It is Micro-C data.
mustache -f input.mcool -ch chr3R  -r 1000 -o output.tsv -p 16 -pt .05 -cz dm6.chrom.sizes -st 0.7

I am currently running it many times with multiple values for -r.

**Comment by ay-lab** [comment]
Let me know how it works/worked for 1kb. I would also try -st 08-0.88 (especially when I am getting loops that don't make sense).

**Comment by gabedolpten** [comment]
Does -r have to be in multiples of "kb"? For example can you run 500 base pairs? with -r 500?

**Comment by ay-lab** [comment]
Yes, you can if your cooler file has that resolution.
