### ISSUE TITLE
Text format input, chromosome naming mustache internal inconsistent with input file

### ISSUE THREAD

**Issue by sf-nevermore** [ay-lab/mustache#14]
Hi,

Thank you for developing such a great tool for loop calling. 

I used "text format" as input which chromosome naming follows "chrn", e.g. "chr1", pattern.  However, to run mustache, -ch parameter has to set as `-ch 1` rather than `-ch chr1`. And the output bedpe loop result also using "1" as chromosome name which is inconsistence with the input. Will that be a quick fix that I can modify in the source code?

Thank you,
Hanbin

**Comment by ay-lab** [comment]
Hi, thank you for using our tool. It should be a quick fix. I'll fix that either today or tomorrow and will let you know.

**Comment by ay-lab** [comment]
The code and pip are updated now.

**Comment by sf-nevermore** [comment]
That will save me a lot of parsing works. Thank you.
