### ISSUE TITLE
mustache crashing on normalization step for small .cool files

### ISSUE THREAD

**Issue by mblanche** [ay-lab/mustache#18]
Hi, new problem found that makes using mustache in a production environment challenging. This is more a request than a bug report I think. Anyhow, would help us tremendously if this would be addressed. 

thanks a lot

**Problem:**
mustache do not terminate gracefully on small .cool file during normalization step

**Requested behavior:**
It would be optimal for mustache to gracefully exit with code 0 but produce some messages on the stderr reporting it's inability to finish normalization. Additionally, a .tsv file with no reported loop would be produce.

**How to replicate:**

_Download test data and pull updated docker image:_
```
wget https://dovetail-public.s3-us-west-2.amazonaws.com/publicData/mustacheEx/test_large.cool
wget https://dovetail-public.s3-us-west-2.amazonaws.com/publicData/mustacheEx/test_small.cool
docker pull mblanche/mustache
```

_Running on large cool file terminates gracefully:_
```
$ docker  run -v ${PWD}:/mnt -i mblanche/mustache mustache -p 24 -f /mnt/test_large.cool  -r 5kb -ch chr21 -o test_chr21_large.tsv


The distance limit is set to 2Mbp
Reading contact map...
0 4000000
2000000 6000000
4000000 8000000
...
Block 19 done.
Starting block 15/22...
Block 15 done.
0 loops found for chrmosome=chr21, fdr<0.2 in 90.09sec
```

_Running on smaller subset cool file crashes at the normalization step and do not exit gracefully:_
```
$ docker  run -v ${PWD}:/mnt -i mblanche/mustache mustache -p 24 -f /mnt/test_small.cool  -r 5kb -ch chr21 -o test_chr21_small.tsv


The distance limit is set to 2Mbp
Reading contact map...
0 4000000
2000000 6000000
4000000 8000000
6000000 10000000
8000000 12000000
10000000 14000000
12000000 16000000
14000000 18000000
16000000 20000000
18000000 22000000
20000000 24000000
22000000 26000000
24000000 28000000
26000000 30000000
28000000 32000000
30000000 34000000
32000000 36000000
34000000 38000000
36000000 40000000
38000000 42000000
40000000 44000000
42000000 46000000
44000000 46709982
Normalizing contact map...
Traceback (most recent call last):
  File "/usr/local/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 1078, in main
    o = regulator(f, args.norm_method, args.cooler_do_balance, CHRM_SIZE, args.outdir,
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 906, in regulator
    n = max(max(x), max(y)) + 1
ValueError: max() arg is an empty sequence
```

**Comment by ay-lab** [comment]
I fixed the code. Please give it a  try and let me know if it works. It seems like your test_small.cool doesn't have any balanced data. Also, for .cool files you don't need to provide the resolution (your data was in 1kb). Mustache reads it directly from the file.

**Comment by mblanche** [comment]
Hmm!! Thanks a lot! Make sense… the small number of evidences in the .cool file make the balancing never reach a consensus. Didn’t realized that I was missing that column even tough I had gone through balancing (I would have expected that the balancing column would have been all equal to 1 but eh… I might ping Nezar A. in the Mirny lab to get his take on this…)

As for the the resolution, I didn’t realized that… so, no matter what resolution you pass the -r parameter it will default to the .cool resolution? This is news to me!

Could you confirm the -r question as this will change a lot how I’m building the pipeline

Thanks a lot, you guys are amazingly fast to answer! I’ll rebuild my image and let you know if all is well.

Best,

Marco

**Comment by ay-lab** [comment]
As far as I know, .cool files come in one resolution and .mcool files have multiple. So, there is no need to provide the resolution for .cool files (but it is needed for .mcool).

**Comment by mblanche** [comment]
Yes, your right. For some reason I was assuming that mustache would bin the cool file to fit the -r parameter and create an output at the the -r resolution.

I’m really sorry, I have to admit that I have not read the full documentation and the paper… I’m going on from what one of the scientist in the lab is feeding me with mustache…

So, just to clarify, if I want loop call at different resolution with mustache, I should pass the .mcool file use one of the resolution in the stack?

**Comment by ay-lab** [comment]
Yes, that's right.

**Comment by mblanche** [comment]
Real sorry to keep bugging you, but nothing is printed anymore... I tried a larger .cool file that was returning loops and nothing is being returned. LMK if you want me to share the large file but I think that there is little logic bug...

**How to reproduce**
```
docker pull mblanche/mustache
docker  run -v ${PWD}:/mnt -i mblanche/mustache mustache -p 24 -f /mnt/test_large.cool  -r 1kb -ch chr21 -o test_chr21_large.tsv
```

**Result**
```
The distance limit is set to 2Mbp
Reading contact map...
Your cooler data resolution is 1000
0 4000000
2000000 6000000
4000000 8000000
...
Starting block 21/22...
Block 21 done.
Starting block 19/22...
Block 19 done.
```

**Desired outcome:**

_A file with minimally the TSV header with no additional line if no loops are being reported_

**Comment by ay-lab** [comment]
Yes, it's a small bug that I'll fix tomorrow. Also, for .cool, .mcool or .hic data if you don't specify the chromosome names mustache automatically runs on all the chromosomes and outputs all the results in a single output file that you specify (by -o).

**Comment by ay-lab** [comment]
it should be fixed now.
