### ISSUE TITLE
Different outputs using cooler and hic inputs with the same option.

### ISSUE THREAD

**Issue by Linhua-Sun** [ay-lab/mustache#20]
Hi: 
Thanks for this great tool. We have tested mustache.py for a hic from plants. We adjusted distance by adding "distFilter = 3000000" at line 883 based on https://github.com/ay-lab/mustache/issues/10. Here we got a hic file called Ctrl.hic. I tested mustache from two different input formats: hic and cooler. cooler file was generated by hic2cool and balanced by `cooler balance`. However, results differ a lot as shown below. Using hic file, we got 269 loops, While using cooler file, we got 29 loops.

The detailed process: 

```
hic2cool convert -r 10000 Ctrl.hic temp_Ctrl_10K.cool
cooler balance temp_Ctrl_10K.cool
```

`mustache.py -f temp_Ctrl_10K.cool -ch 1 -r 10kb -o TEST_Ctrl_cooler_outK10_Chr1.tsv -d 10000000`

```
############
10000000
############
Reading contact map...
0 30427671
10000000.0 30427671
20000000.0 30427671
30000000.0 30427671
16.04 seconds to read the contact map
Normalizing the contact map...
5.92 seconds to run the sparse normalization
Loop calling...
Starting block 1/3...
Starting block 2/3...
Starting block 3/3...
Block 1 done.
Block 2 done.
Block 3 done.
29 loops found for chrmosome=1, fdr<0.2 in 30.57sec
```

`mustache.py -f Ctrl.hic -ch 1 -r 10kb -o TEST_Ctrl_hic_outK10_Chr1.tsv -d 10000000`

```
############
10000000
############
Reading contact map...
HiC version:  8
8.47 seconds to read the contact map
Normalizing the contact map...
6.53 seconds to run the sparse normalization
Loop calling...
Starting block 1/3...
Starting block 2/3...
Starting block 3/3...
Block 1 done.
Block 2 done.
Block 3 done.
269 loops found for chrmosome=1, fdr<0.2 in 26.19sec
```
Thanks again!
Linhua

**Comment by ay-lab** [comment]
Hi Linhua, this is probably because of a bug in the new update. I'll fix it today. Please use .hic for now.

**Comment by ay-lab** [comment]
Also, what version you are using? Can you please confirm that you are using the last version (v1.1.3).

**Comment by Linhua-Sun** [comment]
Thanks for your quick reply.
My version is very old (0.2.3). So I have also tested the V1.1.5. However, the results is also a little different.
And more importantly, much fewer loops can be called by the new version with .hic input which is inconsistent with direct visualizations in juicebox.

`mustache -f temp_Ctrl_10K.cool -ch 1 -r 10kb -o NV_Ctrl_cooler_outK10_Chr1.tsv -d 10000000`

```
The distance limit is set to 2Mbp
Reading contact map...
Your cooler data resolution is 10000
0 20000000
18000000 30427670
Normalizing contact map...
Loop calling...
Starting block 1/2...
Starting block 2/2...
Block 2 done.
Block 1 done.
23 loops found for chrmosome=1, fdr<0.2 in 14.52sec
```

`mustache -f Ctrl.hic -ch 1 -r 10kb           -o NV_Ctrl_hic_outK10_Chr1.tsv -d 10000000`

```
The distance limit is set to 2Mbp
Reading contact map...
0 20000000
HiC version:  8
18000000 30427670
HiC version:  8
Normalizing contact map...
Loop calling...
Starting block 1/2...
Starting block 2/2...
Block 1 done.
Block 2 done.
36 loops found for chrmosome=1, fdr<0.2 in 17.54sec
```

**Comment by ay-lab** [comment]
I am not really sure what's causing the issue. Have you looked at the loops to see which one makes more sense visually (using juicebox)?

**Comment by Linhua-Sun** [comment]
Yes, we checked the juicebox with loops. It seems that loops from .hic are more reliable.

**Comment by ay-lab** [comment]
I would be happy to look into the problem if you can share some plant data with me. I have never tested mustache on plants. The results are very similar between the .cool and .hic human/mouse data I have.

**Comment by Linhua-Sun** [comment]
Sorry for the delay. Sure, thanks. I will send to you by e-mail.

**Comment by Linhua-Sun** [comment]
I'm sorry if I troubled you. Have your ever received the e-mail from jshaslh@163.com. I have sent to you the datasets (hic and cooler files).
