### ISSUE TITLE
Differential option

### ISSUE THREAD

**Issue by gabedolpten** [ay-lab/mustache#24]
Hi, can you explain how the differential loop calling works? Does it just call loops separately on both datasets or is there some merging procedure to make sure it doesnt call a loop in condition 1 and the same loop, two pixels, over in condition 2? 

Additionally, does it account for read depth differences in the two Hi-C files? It should do this when calculating O/E, correct?

**Comment by gabedolpten** [comment]
One last thing – how do I call this from the command line?

**Comment by ay-lab** [comment]
Hi, no it's actually using a combination of mustache and selfish to decide. You just need to input the normalized data (if you don't it uses the the default which is KR). There is an example code on the main readme page: 

python3 ./mustache/mustache/diff_mustache.py -f1 data1.hic -f2 data2.hic -pt 0.05 -pt2 0.1 -o output -r 10000 -st 0.8

**Comment by gabedolpten** [comment]
Great, thanks!
One thing I have noticed is that Mustache sometimes seems to call loops a little bit off-center. Is there any reason for this or any way this can be corrected?

**Comment by ay-lab** [comment]
NP. There can be multiple reasons:
1- there are always FPs and that's true for all methods
2- mustache loops are circular regions (with different scales) in the contact map whose centers are not necessarily the strongest pixels in the region. There is actually a tradeoff between calling the strongest pixels as loops and the reporiducibility.
You can always apply your own simple postprocessing step/s to filter out the loops you don't like.
