### ISSUE TITLE
Different number of loops when I'm using diff_mustache.py

### ISSUE THREAD

**Issue by EnrichettaMileti** [ay-lab/mustache#32]
Hi!
I’m using the new differential tool detection of mustache and I have a question regarding the results.
I’m doing pairwise analysis of 3 samples : e.g A, B and C

When I’m doing A vs B and  I'm obtaining 6,090 loops for sample A
But, when I’m doing the A vs C and  I'm obtaining 7,548 loops for sample A

I would expect that the number of loops is the same, or maybe I’m missing something?

The parameters that I’m using are: -r 10000 -st 0.8 -norm KR -pt 0.05 -pt 2 0.1

**Comment by ay-lab** [comment]
Hi Enrichetta, no you should get the same number of loops for A (assuming the order is the same). Thanks for letting us know, I'll look into that.

**Comment by ay-lab** [comment]
Hi Enrichetta, sorry for the long delay. I ran diff_mustache on different datasets and wasn't able to reproduce the issue you mentioned. Can you make sure you are inputting A always as the first (or second) file. I'd be happy to take a look at your data if you share it with me (abbas@lji.org). 

```
python ./mustache/diff_mustache.py -f1 A.hic  -f2  B.hic  -pt 0.1 -pt2 0.001 -o AB -r 10000 -st 0.8 
python ./mustache/diff_mustache.py -f1 A.hic  -f2  C.hic  -pt 0.1 -pt2 0.001 -o AC -r 10000 -st 0.8 
```
