### ISSUE TITLE
TypeError: nan_to_num() got an unexpected keyword argument 'neginf'

### ISSUE THREAD

**Issue by fboellmann** [ay-lab/mustache#34]
Hi there,
Trying to process fairly deep .hic data set. Got default test analysis to work but when submitting this command to my cluster the pipeline crashes:
mustache.py -f $(pwd)/E1.inter_1.hic -ch 1 -r 5kb -pt 0.01 -o $(pwd)/E1.VC_SQRT.q1.r10kb.p0.1.out.tsv >$(pwd)/mustache/E1/E1.VC_SQRT.q1.r10kb.p0.1.log 2>&1

The distance limit is set to 2Mbp
Reading contact map...
0 10000000
8000000 18000000
16000000 26000000
24000000 34000000
32000000 42000000
40000000 50000000
48000000 58000000
56000000 66000000
64000000 74000000
72000000 82000000
80000000 90000000
88000000 98000000
96000000 106000000
104000000 114000000
112000000 122000000
120000000 130000000
128000000 138000000
136000000 146000000
144000000 154000000
152000000 162000000
160000000 170000000
168000000 178000000
176000000 186000000
184000000 194000000
192000000 202000000
200000000 210000000
208000000 218000000
216000000 226000000
224000000 234000000
232000000 242000000
240000000 248956421
Normalizing contact map...
Traceback (most recent call last):
  File "/home/frank/tools/mustache/mustache/mustache.py", line 1178, in <module>
    main()
  File "/home/frank/tools/mustache/mustache/mustache.py", line 1148, in main
    octaves=args.octaves)
  File "/home/frank/tools/mustache/mustache/mustache.py", line 961, in regulator
    pval_weights = normalize_sparse(x, y, v, res, distance_in_px)
  File "/home/frank/tools/mustache/mustache/mustache.py", line 720, in normalize_sparse
    neginf=std2, posinf=std2, nan=std2)
**TypeError: nan_to_num() got an unexpected keyword argument 'neginf'**

Any help would be greatly appreciated.

F

**Comment by ay-lab** [comment]
Hi, thanks for using our tool. You probably need to update your numpy: pip install numpy --upgrade

**Comment by fboellmann** [comment]
That did the trick. Much appreciated. 
I did not see a tool to merge loop calls from different bin sizes. bedtools pairtopair only reports the overlap but does not merge the combined regions. HiCCUPS does that automatically. Did I miss something in your tool kit?

**Comment by ay-lab** [comment]
No, we just don't have a merger at the moment.

**Comment by fboellmann** [comment]
Thanks a bunch.
