### ISSUE TITLE
Calculation of distance limit?

### ISSUE THREAD

**Issue by fboellmann** [ay-lab/mustache#35]
Since I specified -d 250000000, I can see that the actual max distance metric is 2000 fold higher than my bin size (6Mb, 10Mb, 20Mb for 3k, 5k 10k bin size). Is that hard coded or does that take available RAM into consideration? I am evaluating mustache for shorter loops anyways, so no biggie, just curious.

**Comment by ay-lab** [comment]
Hi, yes it is hardcoded. RAM is one of the reasons. The main reason is that detecting more distant loops comes with the price of missing some short distance loops. You can hardcode the distance you want by uncommenting and changing the line#1048 (#distFilter = 4000000).
