### ISSUE TITLE
mustache.py does not take .hic file as input

### ISSUE THREAD

**Issue by Michael-Szalay** [ay-lab/mustache#39]
I'm trying to run mustache.py with my .hic files, but I am getting the following error: 

```
mustache.py  -f ./micro-c/hic_out_test_length/hic_results/50bp_allValidPairs.hic -ch 1 -r 5kb -o chr1_out5.tsv -pt 0.1 -st 0.8

The distance limit is set to 2Mbp

Reading contact map...
Traceback (most recent call last):
  File "./mustache/mustache/mustache.py", line 1178, in <module>
    main()
  File "./mustache/mustache/mustache.py", line 1135, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "./mustache/mustache/mustache.py", line 946, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome,chromosome2, res)
  File "./mustache/mustache/mustache.py", line 378, in read_hic_file
    chrs, resolutions, masterindex, genome, metadata = read_header(hic)
  File "./mustache/mustache/mustache.py", line 250, in read_header
    key = readcstr(req)
  File "./mustache/mustache/mustache.py", line 210, in readcstr
    return buf.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1: invalid start byte
```

I tried my .hic files from the allValidPairs.file from HiC-Pro, converted with Juicer Tools Version 2.13.06.

I have no problem using the /mustache/data/chr21_5kb.RAWobserved file and the .hic format file for HFFc6 Micro-C from [4D Nucleome Data Portal 4DNFIPC7P27B.hic. 

What could I do?

**Comment by ay-lab** [comment]
Has this issue been resolved after the recent update? Thanks

**Comment by Michael-Szalay** [comment]
hello, unfortunately, no I still have a problem.

now I think he can read the .hic file but I get another errors

1. he does not recognize the chromosome selected just with numbers: 

mustache -f /work/cavalli/mszalay/micro-c/hic_out_test_length/hic_results/50bp_allValidPairs.hic -ch 1 -r 1kb -pt 0.01 -o hic_out_50bp.tsv


The distance limit is set to 2000000bp
Reading contact map...
0 4000000
1 not found in the file.

This was easy to correct, the name has to be with chr...

2. But then a different error popped up:
mustache -f /work/cavalli/mszalay/micro-c/hic_out_test_length/hic_results/50bp_allValidPairs.hic -ch chr1 -r 1kb -pt 0.01 -o hic_out_50bp.tsv


The distance limit is set to 2000000bp
Reading contact map...
0 4000000
File did not contain KR normalization vectors for one or both chromosomes at 1000 BP
Traceback (most recent call last):
  File "/home/cavalli/work/mdistefano/anaconda3/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/cavalli/work/mdistefano/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1055, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/cavalli/work/mdistefano/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 868, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome, chromosome2, res)
  File "/home/cavalli/work/mdistefano/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 324, in read_hic_file
    temp = hicstraw.straw("observed", "KR", f, str(chr1) + ":" + str(int(start)) + ":" + str(int(end)),
MemoryError: std::bad_alloc
 
do you have any idea why this happens? the test data worked again without any problem.

PS: i deleted and I tried to reinstall it completly. I had quite some problems this time with the installation. the environment file did not work without errors. as an example the pypairix==0.3.7 package was difficult to install and also the hic-straw was a problem. I saw mustache needs now hic-straw==1.3.0, but in the environment file it is still hic-straw==0.0.6, this created some problems in the installation. now it works with the test data as before

**Comment by ay-lab** [comment]
Seems like the normalization did not converge for at least one or some of your chromosomes, the error message states that "File did not contain KR normalization vectors for one or both chromosomes at 1000 BP". So I bet if you look into KR normalization vectors, you will see all "inf" for one/some chr. If that is not an important chromosome you can remove them. If that is the case all throughout then: 1) your data is not deep enough for 1kb analysis, 2) the normalization somehow doesn't work and you will need to look for alternative ways to normalize your data.

**Comment by Michael-Szalay** [comment]
thanks for your answer. I looked up the normalization and indeed it was not available at that resolution.
