### ISSUE TITLE
Mustache and ChIA-PET experiments

### ISSUE THREAD

**Issue by jakublipinski** [ay-lab/mustache#4]
Thanks for the Mustache tool. It's extremely fast and well written.

I have a following question: can I use Mustache with ChIA-PET experiments? I tried to run it on [CTCF-targeted ChIA-PET on GM12878](https://data.4dnucleome.org/files-processed/4DNFIMH3J7RW/#file-overview) with the following parameters:
```
pip install mustache-hic cooler
wget https://data.4dnucleome.org/files-processed/4DNFIMH3J7RW/@@download/4DNFIMH3J7RW.mcool
cooler balance --nproc 16 4DNFIMH3J7RW.mcool::/resolutions/5000

mustache -f 4DNFIMH3J7RW.mcool -r 5kb -o mustache_output_5kb.tsv -ch chr1 -st 0.6 -pt 0.3 -p 16
```
but got only about `200` chromatin loops detected in `chr1`. 

The [HiCPeaks](https://github.com/XiaoTaoWang/HiCPeaks) reports aprox. `2400` loops in `chr1` while run:
```
pip install cooler statsmodels sklearn matplotlib hicpeaks
wget https://data.4dnucleome.org/files-processed/4DNFIMH3J7RW/@@download/4DNFIMH3J7RW.mcool
cooler balance --nproc 16 4DNFIMH3J7RW.mcool::/resolutions/5000
pyHICCUPS -O pyhiccups_5kb_chr1.tsv -p 4DNFIMH3J7RW.mcool::/resolutions/5000 --pw 4 --ww 7 --only-anchors --nproc 16 -C 1
```

Is such difference by design? Should use different parameters while analyzing `ChIA-PET` experiments?

**Comment by ay-lab** [comment]
Hi Jakub, thanks for using our tool. We haven't tested mustache on ChIA-PET yet. I'll run it on the data and let you know. In the meantime you can try a lower sparsity test value, e.g., -st 0.7

**Comment by jakublipinski** [comment]
Thanks @ay-lab for your prompt reply. I'm looking forward to the result of your test.

As per my example I tried even lower sparsity test value `-st 0.6`.
