### ISSUE TITLE
potential incorrect variable name

### ISSUE THREAD

**Issue by tzcoolman** [ay-lab/mustache#47]
Hi, 

Thank you for providing the tool. If I am not mistaken, the variable here should be 'f1' not 'f'

https://github.com/ay-lab/mustache/blob/896f5365279c4abd1d88df22d979d1a73384a23b/mustache/diff_mustache.py#L794

This caused program crash when I was running mustache_diff

**Comment by ay-lab** [comment]
Thanks, I fixed it. It was changed by a mistake and it wasn't producing any error running on single chromosomes!
