### ISSUE TITLE
"max() arg is an empty sequence" error

### ISSUE THREAD

**Issue by dixonlab** [ay-lab/mustache#5]
Hello,
We are trying the tool on some data in the lab using a *.hic file as the input. We ran it through all chromosomes (1-22), and all expect chr1 worked fine. We got the following error running it on chr1:

------------------------------------------------------------------------------------------------
The distance limit is set to 2Mbp
Reading contact map...
HiC version:  8
Normalizing contact map...
Traceback (most recent call last):
  File "/usr/local/bin/mustache", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/mustache/mustache.py", line 904, in main
    octaves=args.octaves)
  File "/usr/local/lib/python3.6/site-packages/mustache/mustache.py", line 768, in regulator
    n = max(max(x), max(y)) + 1
ValueError: max() arg is an empty sequence
------------------------------------------------------------------------------------------------

Any thoughts? Like I said, all the other chromosomes were fine, and this was specific to chr1. Thanks.
-Jesse

**Comment by ay-lab** [comment]
Hi, thanks for using our tool. That's weird. I just ran it on chr1 of GM12878 with and without -cz and they both ran fine. What version/data/resolution are you using? Also, can you run it with the -cz and see if it still gives you the error?

**Comment by dixonlab** [comment]
Thanks for replying. We tried running it with the chromosome size file specified but get the same error in the end. We are using some of our own data at 5kb. I'm not sure what the version of mustache we are running is. It doesn't seem like there is a "--version" option, but we installed it recently via pip. I have a guess at what part of the problem is. For this specific file, it for whatever reason doesn't reach convergence at 5kb using the KR normalization when generating the *.hic file for chromosome 1 but does so for all other chromosomes. We have added genome wide KR ("GW_KR") normalization and that converges to 5kb, but I'm not sure if there is an option for specifying different normalization methods from the *.hic file with this tool.

**Comment by ay-lab** [comment]
That was one of my guesses too. Sorry for the inconvenience, right now for .hic data it's only accepting KR and VC. I'll add an input argument so that one can input his desired normalization method. In the meantime, you can run it on .cool format.

**Comment by ay-lab** [comment]
I added the -norm argument and updated the github and pypi. You can now run mustache with "-norm GW_KR". Please let us know how it goes.

**Comment by ay-lab** [comment]
I can take a closer look at the problem if you can share with me some example data.
