### ISSUE TITLE
First 20MB of called loops missing for each chromosome.

### ISSUE THREAD

**Issue by tolender** [ay-lab/mustache#50]
Hi,

I am testing out Mustache for several hic samples and found when checking the loops on Juicer that there is no loops called for the first 20MB of all chromosomes. This is the case for all hic normalizations and all .hic files I've tried. I noticed the first segment of genome for each chromosome is 0 to 20000000, is this related?

Thanks

Below is output for chr1 for one of my samples.

The distance limit is set to 2000000bp
Reading contact map...
0 20000000
18000000 38000000
36000000 56000000
54000000 74000000
72000000 92000000
90000000 110000000
108000000 128000000
126000000 146000000
144000000 164000000
162000000 182000000
180000000 200000000
198000000 218000000
216000000 236000000
234000000 248956421
Normalizing contact map...
Loop calling...
Starting block 1/14...
Block 1 done.
Starting block 8/14...
Block 8 done.
Starting block 7/14...
Block 7 done.
Starting block 5/14...
Block 5 done.
Starting block 6/14...
Block 6 done.
Starting block 4/14...
Block 4 done.
Starting block 2/14...
Block 2 done.
Starting block 9/14...
Block 9 done.
Starting block 3/14...
Block 3 done.
Starting block 10/14...
Block 10 done.
Starting block 11/14...
Block 11 done.
Starting block 13/14...
Block 13 done.
Starting block 14/14...
Block 14 done.
Starting block 12/14...
Block 12 done.
1471 loops found for chrmosome=chr1, fdr<0.2 in 64.72sec

**Comment by roayaei** [comment]
Hi, are you using the last version (1.3.1)?

**Comment by tolender** [comment]
I used _pip3 install mustache-hic_ and the version that was installed was 1.2.7

**Comment by tolender** [comment]
Installing v1.3.1 solves the problem, thank you!
