### ISSUE TITLE
Error: Couldn't find specified contact files

### ISSUE THREAD

**Issue by biohubx** [ay-lab/mustache#6]
Hi,
  
I ran the following code:
mustache -f _raw contatc map path_ -m _raw matrix from HiC-Pro_ -norm ICE -bed _raw bias file from HiC-Pro_

I got the Error: Couldn't find specified contact files

do you know how to deal with this issue?
Best,

**Comment by ay-lab** [comment]
Hi, if you are running on raw text format contact maps use this format: "mustache -f ./data/chr21_5kb.RAWobserved -b ./data/YOUR_BIAS_FILE -ch 21 -r 5kb -pt 0.1 -o chr21_out.tsv -st 0.8". You have to specify 
If you are running on .hic (or .cool) use this format: "mustache -f ./4DNFIPC7P27B.hic -ch 1 -r 5kb -pt 0.01 -o hic_out.tsv -norm NORMALIZATION_METHOD"
If .hic doesn't provide that normalization it will give you an error.

**Comment by benxiahu** [comment]
Thanks, 
     If I ran on raw text format contact maps, I should provide _the raw contatc map_, not the PATH containing raw contatc matrix, for _-f_ parameter, right?
      
    what is the difference in _-b_ and _-bed_ parameters?

   It is necessary to use  _-m_ and _-bed_ parameters?
Best,
