### ISSUE TITLE
Track files not accessible

### ISSUE THREAD

**Issue by stfacc** [ay-lab/mustache#64]
The tracks in all  `WashU-output/*.json` configuration files are not accessible.

For examples, when I try to download `https://informaticsdata.liai.org/BioAdHoc/Groups/vd-ay/abbas/epgBrowser/HFFc6_HiC_5000_all.bed.gz` I'm asked a username/password.

Are the tracks now available at another location?

Many thanks.

**Comment by ay-lab** [comment]
These are made available through this google drive for now: 
https://drive.google.com/drive/folders/1cRE6yPjHtS-0-MSUaL5sug--BPIqhmjT?usp=drive_link
Will update again when the issue is fixed
