### ISSUE TITLE
How to adjust genomic distance by -d option?

### ISSUE THREAD

**Issue by Linhua-Sun** [ay-lab/mustache#7]
Hi, thanks for the great tools! I tried mustache to call loops from high resolution Hi-C datasets of a species with a compact genome (~ 180 Mb). My loops of interest are relative long (1M - 10M).Since limited loops can be found near the diagonal, I am more interested in long-range chromatin interactions. So I want to extend the distance of two loci to be larger. Mustache can found loops < 2 Mb. I changed the -d option. But it always return with 2Mb. I also checked the code. I don't understand why the distance filter are designed in this way? 
```python
    distFilter = parseBP(args.distFilter)#change
    if not distFilter: 
        if 200*res >= 2000000:
            distFilter = 200*res
            print("The distance limit is set to {}bp".format(200*res))
        elif 2000*res <= 2000000:
            distFilter = 2000*res
            print("The distance limit is set to {}bp".format(2000*res))
        else:
            distFilter = 2000000
            print("The distance limit is set to 2Mbp")			
    elif distFilter < 200*res:
        print("The distance limit is set to {}bp".format(200*res))
        distFilter = 200*res
    elif distFilter > 2000*res:
        print("The distance limit is set to {}bp".format(2000*res))
        distFilter = 2000*res
    elif distFilter > 2000000:
        distFilter = 2000000
        print("The distance limit is set to 2Mbp")
```

**Comment by ay-lab** [comment]
Hi Linhua-Sun, thanks for using the mustache. That setting is on purpose as with the current formulation in the master branch mustache can work reliably only for high seq depth experiments within the 2Mb range distance. However, we have been working on extending the distance range by using some variation of the chunking algorithm which is available on the chunking branch of mustache. The chunking implementation is not as reliable/tuned as the main, so If you roughly know what you expect from your data and can share it with me I would be happy to run it for you and let you know about the results (it would also help me to make the implementation better).

**Comment by Linhua-Sun** [comment]
Oh, that's great! Can you give me an e-mail address? I can attach my cool file. I have 1 kb, 5 kb, 10 kb, etc resolution Hi-C cool files. Which one is better? Thanks you for your help!
And I will try the chunking version. Thanks again!

**Comment by ay-lab** [comment]
Sure. For your data I think the 5kb should be better. My email address is abbas@lji.org

**Comment by Linhua-Sun** [comment]
Thanks! I have sent you the file (jshaslh@163.com).
